### ISSUE TITLE
invalid date in response header

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-http#27]
Shouldn't that be catched?

``` shell
[Zend\Http\Header\Exception\InvalidArgumentException]
Invalid date passed as string (0)

[Exception]
DateTime::__construct(): Failed to parse time string(0) at position 0 (0): Unexcepted character
```

---

Originally posted by @aight8 at https://github.com/zendframework/zend-http/issues/9

**Comment by weierophinney** [comment]
Can you add informations?? 
code for example..

You can try to see this link http://stackoverflow.com/questions/17673102/php-datetime-failed-to-parse-time-string


---

Originally posted by @gianarb at https://github.com/zendframework/zend-http/issues/9#issuecomment-118672025

**Comment by weierophinney** [comment]
@aight8 Please provide a way to reproduce this; right now, the exception stack you're listing seems reasonable, but I'm not sure how you got to it, nor what your expectations are.


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-http/issues/9#issuecomment-118853641

**Comment by weierophinney** [comment]
Hi, @weierophinney 

We have the same issue. 

The error is thrown because of Fri, 04 Dec 2015 09:58:06 GMT + 1 the space between  GMT and the + and the 1. Fri, 04 Dec 2015 09:58:06 GMT+1 parses without any issue.

see the trace.

```
2015-12-04T17:30:35+01:00 ERR (3): Exception:
1: Invalid date passed as string (Fri, 04 Dec 2015 09:58:06 GMT + 1)
2: DateTime::__construct(): Failed to parse time string (Fri, 04 Dec 2015 09:58:06 GMT + 1) at position 30 : Unexpected character +
Trace:
#0 /vendor/zendframework/zend-http/src/Header/AbstractDate.php(86): Zend\Http\Header\AbstractDate->setDate('Fri, 04 Dec 201...')
#1 /vendor/zendframework/zend-http/src/Headers.php(448): Zend\Http\Header\AbstractDate::fromString('Last-Modified: ...')
#2 /vendor/zendframework/zend-http/src/Headers.php(352): Zend\Http\Headers->lazyLoadHeader(5)
#3 /vendor/zendframework/zend-http/src/Response/Stream.php(201): Zend\Http\Headers->current()
#4 /vendor/zendframework/zend-http/src/Client.php(916): Zend\Http\Response\Stream::fromStream('HTTP/1.1 200 OK...', Resource id #11789)
#5 /...php(86): Zend\Http\Client->send()
```

The headers from the server. its not something we have control over its external

```
Cache-Control → private
Connection → close
Content-Encoding → gzip
Content-Length → 20
Content-Type → text/xml; charset=UTF-8
Date → Mon, 07 Dec 2015 09:30:02 GMT
Expires →
Expires
Gives the date/time after which the response is considered stale
Mon, 26 Jul 1997 05:00:00 GMT
Last-Modified → Sun, 06 Dec 2015 09:58:06 GMT + 1
Pragma → public
Server → Apache
Vary → Accept-Encoding
X-Powered-By → PHP/5.3.23
```

the datetime headers differ because I've refetched the headers just now. But you see the spaces still being added.


---

Originally posted by @muhammedeminakbulut at https://github.com/zendframework/zend-http/issues/9#issuecomment-162462956

**Comment by weierophinney** [comment]
One could argue that the header value is wrong and therefor it makes sense that the exception is thrown. The problem is that because of that exception, parsing of the the other headers stops so you can't do anything with the response anymore.


---

Originally posted by @waltertamboer at https://github.com/zendframework/zend-http/issues/9#issuecomment-162464580

**Comment by weierophinney** [comment]
It seems to occur if you use $client->setStream($xyz);


---

Originally posted by @muhammedeminakbulut at https://github.com/zendframework/zend-http/issues/9#issuecomment-165501293

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> You can continue using laminas/laminas-http safely.
> Its successor will be [PSR-7](https://www.php-fig.org/psr/psr-7/) in a later revision of laminas/laminas-mvc.
